apiVersion: batch/v1
kind: Job
metadata:
  labels:
    k8s-user: cgu3
  name: sft
  namespace: yn-gpu-workload
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - env:
        - name: HOME
          value: /rsrch5/home/biostatistics/YOUR_USER_NAME
        - name: MODEL
          value: ${MODEL}
        - name: DATASET
          value: ${DATASET}
        - name: HF_TOKEN
          value: ${HF_TOKEN}
        image: hpcharbor.mdanderson.edu/zzhang19/sft:debug
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          limits:
            cpu: '48'
            memory: 1200Gi
            nvidia.com/gpu: '8'
        volumeMounts:
        - mountPath: /dev/shm
          name: shm
        - mountPath: /rsrch5/home/biostatistics/YOUR_USER_NAME
          name: home
      nodeSelector:
        nvidia.com/gpu.present: 'true'
        nvidia.com/gpu.product: NVIDIA-H100-80GB-HBM3
      restartPolicy: Never
      securityContext:
        fsGroup: 600567
        runAsGroup: 600567
        runAsUser: xxxxxx
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 1200Gi
        name: shm
      - name: home
        persistentVolumeClaim:
          claimName: YOUR_USER_NAME-gpu-home
  ttlSecondsAfterFinished: 60
